<%@ include file="/html/taglib/alloy/init.jsp" %>

<%
java.lang.String NAMESPACE = "alloy:image-gallery:";

Map<String, Object> dynamicAttributes = (Map<String, Object>)request.getAttribute("alloy:image-gallery:dynamicAttributes");
Map<String, Object> scopedAttributes = (Map<String, Object>)request.getAttribute("alloy:image-gallery:scopedAttributes");

Map<String, Object> options = new HashMap<String, Object>();

options.putAll(scopedAttributes);
options.putAll(dynamicAttributes);

%>

<%@ include file="/html/taglib/alloy/init-alloy.jsp" %>

<%
java.util.HashMap _align = JSONFactoryUtil.getHashMap(GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:align")));
java.lang.Boolean _anim = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:anim"), true);
java.lang.Object _arrowLeftEl = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:arrowLeftEl"));
java.lang.Object _arrowRightEl = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:arrowRightEl"));
java.lang.Boolean _autoPlay = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:autoPlay"), false);
java.lang.Object _imagegalleryBodyContent = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:imagegalleryBodyContent"));
java.lang.String _caption = GetterUtil.getString((java.lang.String)request.getAttribute("alloy:image-gallery:caption"));
java.lang.Object _captionEl = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:captionEl"));
java.lang.Boolean _captionFromTitle = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:captionFromTitle"), true);
java.lang.Boolean _centered = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:centered"), true);
java.lang.Object _closeEl = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:closeEl"));
java.lang.Object _constrain = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:constrain"));
java.lang.String _cssClass = GetterUtil.getString((java.lang.String)request.getAttribute("alloy:image-gallery:cssClass"));
java.lang.Number _currentIndex = GetterUtil.getNumber(String.valueOf(request.getAttribute("alloy:image-gallery:currentIndex")), 0);
java.lang.Number _delay = GetterUtil.getNumber(String.valueOf(request.getAttribute("alloy:image-gallery:delay")), 7000);
java.lang.Boolean _destroyed = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:destroyed"), false);
java.lang.Boolean _disabled = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:disabled"), false);
java.lang.Object _fillHeight = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:fillHeight"));
java.lang.Boolean _focused = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:focused"), false);
java.lang.Object _footerContent = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:footerContent"));
java.lang.Object _headerContent = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:headerContent"));
java.lang.Object _height = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:height"));
java.lang.String _hideClass = GetterUtil.getString((java.lang.String)request.getAttribute("alloy:image-gallery:hideClass"), "aui-helper-hidden");
java.lang.String _imagegalleryId = GetterUtil.getString((java.lang.String)request.getAttribute("alloy:image-gallery:imagegalleryId"));
java.lang.Object _image = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:image"));
java.util.HashMap _imageAnim = JSONFactoryUtil.getHashMap(GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:imageAnim")));
java.lang.Object _infoEl = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:infoEl"));
java.lang.String _infoTemplate = GetterUtil.getString((java.lang.String)request.getAttribute("alloy:image-gallery:infoTemplate"), "Image {current} of {total}");
java.lang.Boolean _initialized = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:initialized"), false);
java.lang.Object _links = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:links"));
java.lang.Object _loader = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:loader"));
java.lang.Boolean _loading = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:loading"), false);
java.lang.Object _loadingEl = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:loadingEl"));
java.lang.Number _maxHeight = GetterUtil.getNumber(String.valueOf(request.getAttribute("alloy:image-gallery:maxHeight")), 2147483647);
java.lang.Number _maxWidth = GetterUtil.getNumber(String.valueOf(request.getAttribute("alloy:image-gallery:maxWidth")), 2147483647);
java.lang.Object _modal = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:modal"), { opacity: .8, background: '#000' });
java.util.HashMap _paginator = JSONFactoryUtil.getHashMap(GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:paginator")));
java.lang.Object _paginatorEl = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:paginatorEl"));
java.lang.Object _paginatorInstance = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:paginatorInstance"));
java.lang.Boolean _paused = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:paused"), false);
java.lang.String _pausedLabel = GetterUtil.getString((java.lang.String)request.getAttribute("alloy:image-gallery:pausedLabel"));
java.lang.Boolean _playing = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:playing"), false);
java.lang.String _playingLabel = GetterUtil.getString((java.lang.String)request.getAttribute("alloy:image-gallery:playingLabel"), "(Playing)");
java.lang.Boolean _preloadAllImages = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:preloadAllImages"), false);
java.lang.Boolean _preventOverlap = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:preventOverlap"), false);
java.lang.Object _render = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:render"), false);
java.lang.Boolean _rendered = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:rendered"), false);
java.lang.Boolean _repeat = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:repeat"), true);
java.lang.Boolean _shim = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:shim"), false);
java.lang.Boolean _showArrows = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:showArrows"), true);
java.lang.Boolean _showClose = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:showClose"), true);
java.lang.Boolean _showPlayer = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:showPlayer"), true);
java.util.HashMap _strings = JSONFactoryUtil.getHashMap(GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:strings")));
java.lang.Number _tabIndex = GetterUtil.getNumber(String.valueOf(request.getAttribute("alloy:image-gallery:tabIndex")), 0);
java.lang.Object _toolbar = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:toolbar"));
java.lang.Boolean _totalLinks = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:totalLinks"), true);
java.lang.Boolean _useOriginalImage = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:useOriginalImage"), false);
java.lang.Boolean _visible = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:image-gallery:visible"), true);
java.lang.Object _width = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:width"));
java.lang.Number _x = GetterUtil.getNumber(String.valueOf(request.getAttribute("alloy:image-gallery:x")), 0);
java.util.ArrayList _xy = JSONFactoryUtil.getArrayList(GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:xy"), "[0,0]"));
java.lang.Number _y = GetterUtil.getNumber(String.valueOf(request.getAttribute("alloy:image-gallery:y")), 0);
java.lang.Number _zIndex = GetterUtil.getNumber(String.valueOf(request.getAttribute("alloy:image-gallery:zIndex")), 0);
java.lang.Object _afterAlignChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterAlignChange"));
java.lang.Object _afterAnim = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterAnim"));
java.lang.Object _afterAnimChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterAnimChange"));
java.lang.Object _afterArrowLeftElChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterArrowLeftElChange"));
java.lang.Object _afterArrowRightElChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterArrowRightElChange"));
java.lang.Object _afterAutoPlayChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterAutoPlayChange"));
java.lang.Object _afterBodyContentChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterBodyContentChange"));
java.lang.Object _afterBoundingBoxChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterBoundingBoxChange"));
java.lang.Object _afterCaptionChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterCaptionChange"));
java.lang.Object _afterCaptionElChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterCaptionElChange"));
java.lang.Object _afterCaptionFromTitleChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterCaptionFromTitleChange"));
java.lang.Object _afterCenteredChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterCenteredChange"));
java.lang.Object _afterCloseElChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterCloseElChange"));
java.lang.Object _afterConstrainChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterConstrainChange"));
java.lang.Object _afterContentBoxChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterContentBoxChange"));
java.lang.Object _afterCssClassChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterCssClassChange"));
java.lang.Object _afterCurrentIndexChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterCurrentIndexChange"));
java.lang.Object _afterDelayChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterDelayChange"));
java.lang.Object _afterDestroy = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterDestroy"));
java.lang.Object _afterDestroyedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterDestroyedChange"));
java.lang.Object _afterDisabledChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterDisabledChange"));
java.lang.Object _afterFillHeightChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterFillHeightChange"));
java.lang.Object _afterFocusedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterFocusedChange"));
java.lang.Object _afterFooterContentChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterFooterContentChange"));
java.lang.Object _afterHeaderContentChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterHeaderContentChange"));
java.lang.Object _afterHeightChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterHeightChange"));
java.lang.Object _afterHideClassChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterHideClassChange"));
java.lang.Object _afterIdChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterIdChange"));
java.lang.Object _afterImageAnimChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterImageAnimChange"));
java.lang.Object _afterImageChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterImageChange"));
java.lang.Object _afterInfoElChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterInfoElChange"));
java.lang.Object _afterInfoTemplateChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterInfoTemplateChange"));
java.lang.Object _afterInit = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterInit"));
java.lang.Object _afterInitializedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterInitializedChange"));
java.lang.Object _afterLinksChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterLinksChange"));
java.lang.Object _afterLoad = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterLoad"));
java.lang.Object _afterLoaderChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterLoaderChange"));
java.lang.Object _afterLoadingChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterLoadingChange"));
java.lang.Object _afterLoadingElChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterLoadingElChange"));
java.lang.Object _afterMaxHeightChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterMaxHeightChange"));
java.lang.Object _afterMaxWidthChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterMaxWidthChange"));
java.lang.Object _afterModalChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterModalChange"));
java.lang.Object _afterPaginatorChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterPaginatorChange"));
java.lang.Object _afterPaginatorElChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterPaginatorElChange"));
java.lang.Object _afterPaginatorInstanceChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterPaginatorInstanceChange"));
java.lang.Object _afterPausedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterPausedChange"));
java.lang.Object _afterPausedLabelChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterPausedLabelChange"));
java.lang.Object _afterPlayingChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterPlayingChange"));
java.lang.Object _afterPlayingLabelChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterPlayingLabelChange"));
java.lang.Object _afterPreloadAllImagesChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterPreloadAllImagesChange"));
java.lang.Object _afterPreventOverlapChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterPreventOverlapChange"));
java.lang.Object _afterRenderChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterRenderChange"));
java.lang.Object _afterRenderedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterRenderedChange"));
java.lang.Object _afterRepeatChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterRepeatChange"));
java.lang.Object _afterRequest = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterRequest"));
java.lang.Object _afterShimChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterShimChange"));
java.lang.Object _afterShowArrowsChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterShowArrowsChange"));
java.lang.Object _afterShowCloseChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterShowCloseChange"));
java.lang.Object _afterShowPlayerChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterShowPlayerChange"));
java.lang.Object _afterSrcNodeChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterSrcNodeChange"));
java.lang.Object _afterStringsChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterStringsChange"));
java.lang.Object _afterTabIndexChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterTabIndexChange"));
java.lang.Object _afterToolbarChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterToolbarChange"));
java.lang.Object _afterTotalLinksChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterTotalLinksChange"));
java.lang.Object _afterUseOriginalImageChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterUseOriginalImageChange"));
java.lang.Object _afterVisibleChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterVisibleChange"));
java.lang.Object _afterContentUpdate = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterContentUpdate"));
java.lang.Object _afterRender = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterRender"));
java.lang.Object _afterWidthChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterWidthChange"));
java.lang.Object _afterXChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterXChange"));
java.lang.Object _afterXyChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterXyChange"));
java.lang.Object _afterYChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterYChange"));
java.lang.Object _afterZIndexChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:afterZIndexChange"));
java.lang.Object _onAlignChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onAlignChange"));
java.lang.Object _onAnim = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onAnim"));
java.lang.Object _onAnimChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onAnimChange"));
java.lang.Object _onArrowLeftElChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onArrowLeftElChange"));
java.lang.Object _onArrowRightElChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onArrowRightElChange"));
java.lang.Object _onAutoPlayChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onAutoPlayChange"));
java.lang.Object _onBodyContentChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onBodyContentChange"));
java.lang.Object _onBoundingBoxChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onBoundingBoxChange"));
java.lang.Object _onCaptionChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onCaptionChange"));
java.lang.Object _onCaptionElChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onCaptionElChange"));
java.lang.Object _onCaptionFromTitleChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onCaptionFromTitleChange"));
java.lang.Object _onCenteredChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onCenteredChange"));
java.lang.Object _onCloseElChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onCloseElChange"));
java.lang.Object _onConstrainChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onConstrainChange"));
java.lang.Object _onContentBoxChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onContentBoxChange"));
java.lang.Object _onCssClassChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onCssClassChange"));
java.lang.Object _onCurrentIndexChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onCurrentIndexChange"));
java.lang.Object _onDelayChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onDelayChange"));
java.lang.Object _onDestroy = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onDestroy"));
java.lang.Object _onDestroyedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onDestroyedChange"));
java.lang.Object _onDisabledChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onDisabledChange"));
java.lang.Object _onFillHeightChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onFillHeightChange"));
java.lang.Object _onFocusedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onFocusedChange"));
java.lang.Object _onFooterContentChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onFooterContentChange"));
java.lang.Object _onHeaderContentChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onHeaderContentChange"));
java.lang.Object _onHeightChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onHeightChange"));
java.lang.Object _onHideClassChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onHideClassChange"));
java.lang.Object _onIdChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onIdChange"));
java.lang.Object _onImageAnimChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onImageAnimChange"));
java.lang.Object _onImageChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onImageChange"));
java.lang.Object _onInfoElChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onInfoElChange"));
java.lang.Object _onInfoTemplateChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onInfoTemplateChange"));
java.lang.Object _onInit = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onInit"));
java.lang.Object _onInitializedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onInitializedChange"));
java.lang.Object _onLinksChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onLinksChange"));
java.lang.Object _onLoad = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onLoad"));
java.lang.Object _onLoaderChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onLoaderChange"));
java.lang.Object _onLoadingChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onLoadingChange"));
java.lang.Object _onLoadingElChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onLoadingElChange"));
java.lang.Object _onMaxHeightChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onMaxHeightChange"));
java.lang.Object _onMaxWidthChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onMaxWidthChange"));
java.lang.Object _onModalChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onModalChange"));
java.lang.Object _onPaginatorChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onPaginatorChange"));
java.lang.Object _onPaginatorElChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onPaginatorElChange"));
java.lang.Object _onPaginatorInstanceChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onPaginatorInstanceChange"));
java.lang.Object _onPausedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onPausedChange"));
java.lang.Object _onPausedLabelChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onPausedLabelChange"));
java.lang.Object _onPlayingChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onPlayingChange"));
java.lang.Object _onPlayingLabelChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onPlayingLabelChange"));
java.lang.Object _onPreloadAllImagesChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onPreloadAllImagesChange"));
java.lang.Object _onPreventOverlapChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onPreventOverlapChange"));
java.lang.Object _onRenderChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onRenderChange"));
java.lang.Object _onRenderedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onRenderedChange"));
java.lang.Object _onRepeatChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onRepeatChange"));
java.lang.Object _onRequest = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onRequest"));
java.lang.Object _onShimChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onShimChange"));
java.lang.Object _onShowArrowsChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onShowArrowsChange"));
java.lang.Object _onShowCloseChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onShowCloseChange"));
java.lang.Object _onShowPlayerChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onShowPlayerChange"));
java.lang.Object _onSrcNodeChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onSrcNodeChange"));
java.lang.Object _onStringsChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onStringsChange"));
java.lang.Object _onTabIndexChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onTabIndexChange"));
java.lang.Object _onToolbarChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onToolbarChange"));
java.lang.Object _onTotalLinksChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onTotalLinksChange"));
java.lang.Object _onUseOriginalImageChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onUseOriginalImageChange"));
java.lang.Object _onVisibleChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onVisibleChange"));
java.lang.Object _onContentUpdate = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onContentUpdate"));
java.lang.Object _onRender = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onRender"));
java.lang.Object _onWidthChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onWidthChange"));
java.lang.Object _onXChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onXChange"));
java.lang.Object _onXyChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onXyChange"));
java.lang.Object _onYChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onYChange"));
java.lang.Object _onZIndexChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:image-gallery:onZIndexChange"));

_updateOptions(options, "align", _align);
_updateOptions(options, "anim", _anim);
_updateOptions(options, "arrowLeftEl", _arrowLeftEl);
_updateOptions(options, "arrowRightEl", _arrowRightEl);
_updateOptions(options, "autoPlay", _autoPlay);
_updateOptions(options, "imagegalleryBodyContent", _imagegalleryBodyContent);
_updateOptions(options, "boundingBox", _boundingBox);
_updateOptions(options, "caption", _caption);
_updateOptions(options, "captionEl", _captionEl);
_updateOptions(options, "captionFromTitle", _captionFromTitle);
_updateOptions(options, "centered", _centered);
_updateOptions(options, "closeEl", _closeEl);
_updateOptions(options, "constrain", _constrain);
_updateOptions(options, "contentBox", _contentBox);
_updateOptions(options, "cssClass", _cssClass);
_updateOptions(options, "currentIndex", _currentIndex);
_updateOptions(options, "delay", _delay);
_updateOptions(options, "destroyed", _destroyed);
_updateOptions(options, "disabled", _disabled);
_updateOptions(options, "fillHeight", _fillHeight);
_updateOptions(options, "focused", _focused);
_updateOptions(options, "footerContent", _footerContent);
_updateOptions(options, "headerContent", _headerContent);
_updateOptions(options, "height", _height);
_updateOptions(options, "hideClass", _hideClass);
_updateOptions(options, "imagegalleryId", _imagegalleryId);
_updateOptions(options, "image", _image);
_updateOptions(options, "imageAnim", _imageAnim);
_updateOptions(options, "infoEl", _infoEl);
_updateOptions(options, "infoTemplate", _infoTemplate);
_updateOptions(options, "initialized", _initialized);
_updateOptions(options, "links", _links);
_updateOptions(options, "loader", _loader);
_updateOptions(options, "loading", _loading);
_updateOptions(options, "loadingEl", _loadingEl);
_updateOptions(options, "maxHeight", _maxHeight);
_updateOptions(options, "maxWidth", _maxWidth);
_updateOptions(options, "modal", _modal);
_updateOptions(options, "paginator", _paginator);
_updateOptions(options, "paginatorEl", _paginatorEl);
_updateOptions(options, "paginatorInstance", _paginatorInstance);
_updateOptions(options, "paused", _paused);
_updateOptions(options, "pausedLabel", _pausedLabel);
_updateOptions(options, "playing", _playing);
_updateOptions(options, "playingLabel", _playingLabel);
_updateOptions(options, "preloadAllImages", _preloadAllImages);
_updateOptions(options, "preventOverlap", _preventOverlap);
_updateOptions(options, "render", _render);
_updateOptions(options, "rendered", _rendered);
_updateOptions(options, "repeat", _repeat);
_updateOptions(options, "shim", _shim);
_updateOptions(options, "showArrows", _showArrows);
_updateOptions(options, "showClose", _showClose);
_updateOptions(options, "showPlayer", _showPlayer);
_updateOptions(options, "srcNode", _srcNode);
_updateOptions(options, "strings", _strings);
_updateOptions(options, "tabIndex", _tabIndex);
_updateOptions(options, "toolbar", _toolbar);
_updateOptions(options, "totalLinks", _totalLinks);
_updateOptions(options, "useOriginalImage", _useOriginalImage);
_updateOptions(options, "visible", _visible);
_updateOptions(options, "width", _width);
_updateOptions(options, "x", _x);
_updateOptions(options, "xy", _xy);
_updateOptions(options, "y", _y);
_updateOptions(options, "zIndex", _zIndex);
_updateOptions(options, "afterAlignChange", _afterAlignChange);
_updateOptions(options, "afterAnim", _afterAnim);
_updateOptions(options, "afterAnimChange", _afterAnimChange);
_updateOptions(options, "afterArrowLeftElChange", _afterArrowLeftElChange);
_updateOptions(options, "afterArrowRightElChange", _afterArrowRightElChange);
_updateOptions(options, "afterAutoPlayChange", _afterAutoPlayChange);
_updateOptions(options, "afterBodyContentChange", _afterBodyContentChange);
_updateOptions(options, "afterBoundingBoxChange", _afterBoundingBoxChange);
_updateOptions(options, "afterCaptionChange", _afterCaptionChange);
_updateOptions(options, "afterCaptionElChange", _afterCaptionElChange);
_updateOptions(options, "afterCaptionFromTitleChange", _afterCaptionFromTitleChange);
_updateOptions(options, "afterCenteredChange", _afterCenteredChange);
_updateOptions(options, "afterCloseElChange", _afterCloseElChange);
_updateOptions(options, "afterConstrainChange", _afterConstrainChange);
_updateOptions(options, "afterContentBoxChange", _afterContentBoxChange);
_updateOptions(options, "afterCssClassChange", _afterCssClassChange);
_updateOptions(options, "afterCurrentIndexChange", _afterCurrentIndexChange);
_updateOptions(options, "afterDelayChange", _afterDelayChange);
_updateOptions(options, "afterDestroy", _afterDestroy);
_updateOptions(options, "afterDestroyedChange", _afterDestroyedChange);
_updateOptions(options, "afterDisabledChange", _afterDisabledChange);
_updateOptions(options, "afterFillHeightChange", _afterFillHeightChange);
_updateOptions(options, "afterFocusedChange", _afterFocusedChange);
_updateOptions(options, "afterFooterContentChange", _afterFooterContentChange);
_updateOptions(options, "afterHeaderContentChange", _afterHeaderContentChange);
_updateOptions(options, "afterHeightChange", _afterHeightChange);
_updateOptions(options, "afterHideClassChange", _afterHideClassChange);
_updateOptions(options, "afterIdChange", _afterIdChange);
_updateOptions(options, "afterImageAnimChange", _afterImageAnimChange);
_updateOptions(options, "afterImageChange", _afterImageChange);
_updateOptions(options, "afterInfoElChange", _afterInfoElChange);
_updateOptions(options, "afterInfoTemplateChange", _afterInfoTemplateChange);
_updateOptions(options, "afterInit", _afterInit);
_updateOptions(options, "afterInitializedChange", _afterInitializedChange);
_updateOptions(options, "afterLinksChange", _afterLinksChange);
_updateOptions(options, "afterLoad", _afterLoad);
_updateOptions(options, "afterLoaderChange", _afterLoaderChange);
_updateOptions(options, "afterLoadingChange", _afterLoadingChange);
_updateOptions(options, "afterLoadingElChange", _afterLoadingElChange);
_updateOptions(options, "afterMaxHeightChange", _afterMaxHeightChange);
_updateOptions(options, "afterMaxWidthChange", _afterMaxWidthChange);
_updateOptions(options, "afterModalChange", _afterModalChange);
_updateOptions(options, "afterPaginatorChange", _afterPaginatorChange);
_updateOptions(options, "afterPaginatorElChange", _afterPaginatorElChange);
_updateOptions(options, "afterPaginatorInstanceChange", _afterPaginatorInstanceChange);
_updateOptions(options, "afterPausedChange", _afterPausedChange);
_updateOptions(options, "afterPausedLabelChange", _afterPausedLabelChange);
_updateOptions(options, "afterPlayingChange", _afterPlayingChange);
_updateOptions(options, "afterPlayingLabelChange", _afterPlayingLabelChange);
_updateOptions(options, "afterPreloadAllImagesChange", _afterPreloadAllImagesChange);
_updateOptions(options, "afterPreventOverlapChange", _afterPreventOverlapChange);
_updateOptions(options, "afterRenderChange", _afterRenderChange);
_updateOptions(options, "afterRenderedChange", _afterRenderedChange);
_updateOptions(options, "afterRepeatChange", _afterRepeatChange);
_updateOptions(options, "afterRequest", _afterRequest);
_updateOptions(options, "afterShimChange", _afterShimChange);
_updateOptions(options, "afterShowArrowsChange", _afterShowArrowsChange);
_updateOptions(options, "afterShowCloseChange", _afterShowCloseChange);
_updateOptions(options, "afterShowPlayerChange", _afterShowPlayerChange);
_updateOptions(options, "afterSrcNodeChange", _afterSrcNodeChange);
_updateOptions(options, "afterStringsChange", _afterStringsChange);
_updateOptions(options, "afterTabIndexChange", _afterTabIndexChange);
_updateOptions(options, "afterToolbarChange", _afterToolbarChange);
_updateOptions(options, "afterTotalLinksChange", _afterTotalLinksChange);
_updateOptions(options, "afterUseOriginalImageChange", _afterUseOriginalImageChange);
_updateOptions(options, "afterVisibleChange", _afterVisibleChange);
_updateOptions(options, "afterContentUpdate", _afterContentUpdate);
_updateOptions(options, "afterRender", _afterRender);
_updateOptions(options, "afterWidthChange", _afterWidthChange);
_updateOptions(options, "afterXChange", _afterXChange);
_updateOptions(options, "afterXyChange", _afterXyChange);
_updateOptions(options, "afterYChange", _afterYChange);
_updateOptions(options, "afterZIndexChange", _afterZIndexChange);
_updateOptions(options, "onAlignChange", _onAlignChange);
_updateOptions(options, "onAnim", _onAnim);
_updateOptions(options, "onAnimChange", _onAnimChange);
_updateOptions(options, "onArrowLeftElChange", _onArrowLeftElChange);
_updateOptions(options, "onArrowRightElChange", _onArrowRightElChange);
_updateOptions(options, "onAutoPlayChange", _onAutoPlayChange);
_updateOptions(options, "onBodyContentChange", _onBodyContentChange);
_updateOptions(options, "onBoundingBoxChange", _onBoundingBoxChange);
_updateOptions(options, "onCaptionChange", _onCaptionChange);
_updateOptions(options, "onCaptionElChange", _onCaptionElChange);
_updateOptions(options, "onCaptionFromTitleChange", _onCaptionFromTitleChange);
_updateOptions(options, "onCenteredChange", _onCenteredChange);
_updateOptions(options, "onCloseElChange", _onCloseElChange);
_updateOptions(options, "onConstrainChange", _onConstrainChange);
_updateOptions(options, "onContentBoxChange", _onContentBoxChange);
_updateOptions(options, "onCssClassChange", _onCssClassChange);
_updateOptions(options, "onCurrentIndexChange", _onCurrentIndexChange);
_updateOptions(options, "onDelayChange", _onDelayChange);
_updateOptions(options, "onDestroy", _onDestroy);
_updateOptions(options, "onDestroyedChange", _onDestroyedChange);
_updateOptions(options, "onDisabledChange", _onDisabledChange);
_updateOptions(options, "onFillHeightChange", _onFillHeightChange);
_updateOptions(options, "onFocusedChange", _onFocusedChange);
_updateOptions(options, "onFooterContentChange", _onFooterContentChange);
_updateOptions(options, "onHeaderContentChange", _onHeaderContentChange);
_updateOptions(options, "onHeightChange", _onHeightChange);
_updateOptions(options, "onHideClassChange", _onHideClassChange);
_updateOptions(options, "onIdChange", _onIdChange);
_updateOptions(options, "onImageAnimChange", _onImageAnimChange);
_updateOptions(options, "onImageChange", _onImageChange);
_updateOptions(options, "onInfoElChange", _onInfoElChange);
_updateOptions(options, "onInfoTemplateChange", _onInfoTemplateChange);
_updateOptions(options, "onInit", _onInit);
_updateOptions(options, "onInitializedChange", _onInitializedChange);
_updateOptions(options, "onLinksChange", _onLinksChange);
_updateOptions(options, "onLoad", _onLoad);
_updateOptions(options, "onLoaderChange", _onLoaderChange);
_updateOptions(options, "onLoadingChange", _onLoadingChange);
_updateOptions(options, "onLoadingElChange", _onLoadingElChange);
_updateOptions(options, "onMaxHeightChange", _onMaxHeightChange);
_updateOptions(options, "onMaxWidthChange", _onMaxWidthChange);
_updateOptions(options, "onModalChange", _onModalChange);
_updateOptions(options, "onPaginatorChange", _onPaginatorChange);
_updateOptions(options, "onPaginatorElChange", _onPaginatorElChange);
_updateOptions(options, "onPaginatorInstanceChange", _onPaginatorInstanceChange);
_updateOptions(options, "onPausedChange", _onPausedChange);
_updateOptions(options, "onPausedLabelChange", _onPausedLabelChange);
_updateOptions(options, "onPlayingChange", _onPlayingChange);
_updateOptions(options, "onPlayingLabelChange", _onPlayingLabelChange);
_updateOptions(options, "onPreloadAllImagesChange", _onPreloadAllImagesChange);
_updateOptions(options, "onPreventOverlapChange", _onPreventOverlapChange);
_updateOptions(options, "onRenderChange", _onRenderChange);
_updateOptions(options, "onRenderedChange", _onRenderedChange);
_updateOptions(options, "onRepeatChange", _onRepeatChange);
_updateOptions(options, "onRequest", _onRequest);
_updateOptions(options, "onShimChange", _onShimChange);
_updateOptions(options, "onShowArrowsChange", _onShowArrowsChange);
_updateOptions(options, "onShowCloseChange", _onShowCloseChange);
_updateOptions(options, "onShowPlayerChange", _onShowPlayerChange);
_updateOptions(options, "onSrcNodeChange", _onSrcNodeChange);
_updateOptions(options, "onStringsChange", _onStringsChange);
_updateOptions(options, "onTabIndexChange", _onTabIndexChange);
_updateOptions(options, "onToolbarChange", _onToolbarChange);
_updateOptions(options, "onTotalLinksChange", _onTotalLinksChange);
_updateOptions(options, "onUseOriginalImageChange", _onUseOriginalImageChange);
_updateOptions(options, "onVisibleChange", _onVisibleChange);
_updateOptions(options, "onContentUpdate", _onContentUpdate);
_updateOptions(options, "onRender", _onRender);
_updateOptions(options, "onWidthChange", _onWidthChange);
_updateOptions(options, "onXChange", _onXChange);
_updateOptions(options, "onXyChange", _onXyChange);
_updateOptions(options, "onYChange", _onYChange);
_updateOptions(options, "onZIndexChange", _onZIndexChange);
%>

<%@ include file="init-ext.jsp" %>