<%@ include file="/html/taglib/alloy/init.jsp" %>

<%
java.lang.String NAMESPACE = "alloy:textboxlist:";

Map<String, Object> dynamicAttributes = (Map<String, Object>)request.getAttribute("alloy:textboxlist:dynamicAttributes");
Map<String, Object> scopedAttributes = (Map<String, Object>)request.getAttribute("alloy:textboxlist:scopedAttributes");

Map<String, Object> options = new HashMap<String, Object>();

options.putAll(scopedAttributes);
options.putAll(dynamicAttributes);

%>

<%@ include file="/html/taglib/alloy/init-alloy.jsp" %>

<%
java.lang.Boolean _alwaysShowContainer = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:textboxlist:alwaysShowContainer"), false);
java.lang.Boolean _applyLocalFilter = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:textboxlist:applyLocalFilter"), true);
java.lang.Boolean _autoHighlight = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:textboxlist:autoHighlight"), true);
java.lang.Boolean _button = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:textboxlist:button"), true);
java.lang.String _cssClass = GetterUtil.getString((java.lang.String)request.getAttribute("alloy:textboxlist:cssClass"));
java.lang.Object _dataSource = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:dataSource"));
java.lang.String _dataSourceType = GetterUtil.getString((java.lang.String)request.getAttribute("alloy:textboxlist:dataSourceType"));
java.lang.String _delimChar = GetterUtil.getString((java.lang.String)request.getAttribute("alloy:textboxlist:delimChar"));
java.lang.Boolean _destroyed = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:textboxlist:destroyed"), false);
java.lang.Boolean _disabled = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:textboxlist:disabled"), false);
java.lang.Boolean _focused = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:textboxlist:focused"), false);
java.lang.Boolean _forceSelection = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:textboxlist:forceSelection"), false);
java.lang.Object _height = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:height"));
java.lang.String _hideClass = GetterUtil.getString((java.lang.String)request.getAttribute("alloy:textboxlist:hideClass"), "aui-helper-hidden");
java.lang.String _textboxlistId = GetterUtil.getString((java.lang.String)request.getAttribute("alloy:textboxlist:textboxlistId"));
java.lang.Boolean _initialized = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:textboxlist:initialized"), false);
java.lang.String _input = GetterUtil.getString((java.lang.String)request.getAttribute("alloy:textboxlist:input"));
java.lang.Object _matchKey = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:matchKey"), 0);
java.lang.Number _maxResultsDisplayed = GetterUtil.getNumber(String.valueOf(request.getAttribute("alloy:textboxlist:maxResultsDisplayed")), 10);
java.lang.Number _minQueryLength = GetterUtil.getNumber(String.valueOf(request.getAttribute("alloy:textboxlist:minQueryLength")), 1);
java.lang.Number _queryDelay = GetterUtil.getNumber(String.valueOf(request.getAttribute("alloy:textboxlist:queryDelay")), 0.2);
java.lang.Number _queryInterval = GetterUtil.getNumber(String.valueOf(request.getAttribute("alloy:textboxlist:queryInterval")), 0.5);
java.lang.Boolean _queryMatchCase = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:textboxlist:queryMatchCase"), false);
java.lang.Boolean _queryMatchContains = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:textboxlist:queryMatchContains"), false);
java.lang.Boolean _queryQuestionMark = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:textboxlist:queryQuestionMark"), true);
java.lang.Object _render = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:render"), false);
java.lang.Boolean _rendered = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:textboxlist:rendered"), false);
java.util.HashMap _schema = JSONFactoryUtil.getHashMap(GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:schema")));
java.lang.String _schemaType = GetterUtil.getString((java.lang.String)request.getAttribute("alloy:textboxlist:schemaType"), "array");
java.util.HashMap _strings = JSONFactoryUtil.getHashMap(GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:strings")));
java.lang.Boolean _suppressInputUpdate = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:textboxlist:suppressInputUpdate"), false);
java.lang.Number _tabIndex = GetterUtil.getNumber(String.valueOf(request.getAttribute("alloy:textboxlist:tabIndex")), 0);
java.lang.Boolean _typeAhead = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:textboxlist:typeAhead"), false);
java.lang.Number _typeAheadDelay = GetterUtil.getNumber(String.valueOf(request.getAttribute("alloy:textboxlist:typeAheadDelay")), 0.2);
java.lang.String _uniqueName = GetterUtil.getString((java.lang.String)request.getAttribute("alloy:textboxlist:uniqueName"));
java.lang.Boolean _visible = GetterUtil.getBoolean((java.lang.Boolean)request.getAttribute("alloy:textboxlist:visible"), true);
java.lang.Object _width = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:width"));
java.lang.Object _afterAlwaysShowContainerChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterAlwaysShowContainerChange"));
java.lang.Object _afterApplyLocalFilterChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterApplyLocalFilterChange"));
java.lang.Object _afterAutoHighlightChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterAutoHighlightChange"));
java.lang.Object _afterBoundingBoxChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterBoundingBoxChange"));
java.lang.Object _afterButtonChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterButtonChange"));
java.lang.Object _afterContainerCollapse = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterContainerCollapse"));
java.lang.Object _afterContainerExpand = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterContainerExpand"));
java.lang.Object _afterContainerPopulate = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterContainerPopulate"));
java.lang.Object _afterContentBoxChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterContentBoxChange"));
java.lang.Object _afterCssClassChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterCssClassChange"));
java.lang.Object _afterDataError = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterDataError"));
java.lang.Object _afterDataRequest = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterDataRequest"));
java.lang.Object _afterDataReturn = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterDataReturn"));
java.lang.Object _afterDataSourceChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterDataSourceChange"));
java.lang.Object _afterDataSourceTypeChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterDataSourceTypeChange"));
java.lang.Object _afterDelimCharChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterDelimCharChange"));
java.lang.Object _afterDestroy = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterDestroy"));
java.lang.Object _afterDestroyedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterDestroyedChange"));
java.lang.Object _afterDisabledChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterDisabledChange"));
java.lang.Object _afterFocusedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterFocusedChange"));
java.lang.Object _afterForceSelectionChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterForceSelectionChange"));
java.lang.Object _afterHeightChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterHeightChange"));
java.lang.Object _afterHideClassChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterHideClassChange"));
java.lang.Object _afterIdChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterIdChange"));
java.lang.Object _afterInit = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterInit"));
java.lang.Object _afterInitializedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterInitializedChange"));
java.lang.Object _afterInputChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterInputChange"));
java.lang.Object _afterItemArrowFrom = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterItemArrowFrom"));
java.lang.Object _afterItemArrowTo = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterItemArrowTo"));
java.lang.Object _afterItemMouseOut = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterItemMouseOut"));
java.lang.Object _afterItemMouseOver = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterItemMouseOver"));
java.lang.Object _afterItemSelect = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterItemSelect"));
java.lang.Object _afterMatchKeyChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterMatchKeyChange"));
java.lang.Object _afterMaxResultsDisplayedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterMaxResultsDisplayedChange"));
java.lang.Object _afterMinQueryLengthChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterMinQueryLengthChange"));
java.lang.Object _afterQueryDelayChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterQueryDelayChange"));
java.lang.Object _afterQueryIntervalChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterQueryIntervalChange"));
java.lang.Object _afterQueryMatchCaseChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterQueryMatchCaseChange"));
java.lang.Object _afterQueryMatchContainsChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterQueryMatchContainsChange"));
java.lang.Object _afterQueryQuestionMarkChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterQueryQuestionMarkChange"));
java.lang.Object _afterRenderChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterRenderChange"));
java.lang.Object _afterRenderedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterRenderedChange"));
java.lang.Object _afterSchemaChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterSchemaChange"));
java.lang.Object _afterSchemaTypeChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterSchemaTypeChange"));
java.lang.Object _afterSelectionEnforce = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterSelectionEnforce"));
java.lang.Object _afterSrcNodeChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterSrcNodeChange"));
java.lang.Object _afterStringsChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterStringsChange"));
java.lang.Object _afterSuppressInputUpdateChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterSuppressInputUpdateChange"));
java.lang.Object _afterTabIndexChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterTabIndexChange"));
java.lang.Object _afterTextboxBlur = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterTextboxBlur"));
java.lang.Object _afterTextboxChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterTextboxChange"));
java.lang.Object _afterTextboxFocus = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterTextboxFocus"));
java.lang.Object _afterTextboxKey = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterTextboxKey"));
java.lang.Object _afterTypeAhead = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterTypeAhead"));
java.lang.Object _afterTypeAheadChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterTypeAheadChange"));
java.lang.Object _afterTypeAheadDelayChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterTypeAheadDelayChange"));
java.lang.Object _afterUniqueNameChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterUniqueNameChange"));
java.lang.Object _afterUnmatchedItemSelect = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterUnmatchedItemSelect"));
java.lang.Object _afterVisibleChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterVisibleChange"));
java.lang.Object _afterContentUpdate = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterContentUpdate"));
java.lang.Object _afterRender = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterRender"));
java.lang.Object _afterWidthChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:afterWidthChange"));
java.lang.Object _onAlwaysShowContainerChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onAlwaysShowContainerChange"));
java.lang.Object _onApplyLocalFilterChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onApplyLocalFilterChange"));
java.lang.Object _onAutoHighlightChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onAutoHighlightChange"));
java.lang.Object _onBoundingBoxChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onBoundingBoxChange"));
java.lang.Object _onButtonChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onButtonChange"));
java.lang.Object _onContainerCollapse = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onContainerCollapse"));
java.lang.Object _onContainerExpand = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onContainerExpand"));
java.lang.Object _onContainerPopulate = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onContainerPopulate"));
java.lang.Object _onContentBoxChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onContentBoxChange"));
java.lang.Object _onCssClassChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onCssClassChange"));
java.lang.Object _onDataError = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onDataError"));
java.lang.Object _onDataRequest = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onDataRequest"));
java.lang.Object _onDataReturn = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onDataReturn"));
java.lang.Object _onDataSourceChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onDataSourceChange"));
java.lang.Object _onDataSourceTypeChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onDataSourceTypeChange"));
java.lang.Object _onDelimCharChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onDelimCharChange"));
java.lang.Object _onDestroy = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onDestroy"));
java.lang.Object _onDestroyedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onDestroyedChange"));
java.lang.Object _onDisabledChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onDisabledChange"));
java.lang.Object _onFocusedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onFocusedChange"));
java.lang.Object _onForceSelectionChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onForceSelectionChange"));
java.lang.Object _onHeightChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onHeightChange"));
java.lang.Object _onHideClassChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onHideClassChange"));
java.lang.Object _onIdChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onIdChange"));
java.lang.Object _onInit = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onInit"));
java.lang.Object _onInitializedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onInitializedChange"));
java.lang.Object _onInputChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onInputChange"));
java.lang.Object _onItemArrowFrom = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onItemArrowFrom"));
java.lang.Object _onItemArrowTo = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onItemArrowTo"));
java.lang.Object _onItemMouseOut = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onItemMouseOut"));
java.lang.Object _onItemMouseOver = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onItemMouseOver"));
java.lang.Object _onItemSelect = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onItemSelect"));
java.lang.Object _onMatchKeyChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onMatchKeyChange"));
java.lang.Object _onMaxResultsDisplayedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onMaxResultsDisplayedChange"));
java.lang.Object _onMinQueryLengthChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onMinQueryLengthChange"));
java.lang.Object _onQueryDelayChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onQueryDelayChange"));
java.lang.Object _onQueryIntervalChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onQueryIntervalChange"));
java.lang.Object _onQueryMatchCaseChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onQueryMatchCaseChange"));
java.lang.Object _onQueryMatchContainsChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onQueryMatchContainsChange"));
java.lang.Object _onQueryQuestionMarkChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onQueryQuestionMarkChange"));
java.lang.Object _onRenderChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onRenderChange"));
java.lang.Object _onRenderedChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onRenderedChange"));
java.lang.Object _onSchemaChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onSchemaChange"));
java.lang.Object _onSchemaTypeChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onSchemaTypeChange"));
java.lang.Object _onSelectionEnforce = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onSelectionEnforce"));
java.lang.Object _onSrcNodeChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onSrcNodeChange"));
java.lang.Object _onStringsChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onStringsChange"));
java.lang.Object _onSuppressInputUpdateChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onSuppressInputUpdateChange"));
java.lang.Object _onTabIndexChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onTabIndexChange"));
java.lang.Object _onTextboxBlur = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onTextboxBlur"));
java.lang.Object _onTextboxChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onTextboxChange"));
java.lang.Object _onTextboxFocus = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onTextboxFocus"));
java.lang.Object _onTextboxKey = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onTextboxKey"));
java.lang.Object _onTypeAhead = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onTypeAhead"));
java.lang.Object _onTypeAheadChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onTypeAheadChange"));
java.lang.Object _onTypeAheadDelayChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onTypeAheadDelayChange"));
java.lang.Object _onUniqueNameChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onUniqueNameChange"));
java.lang.Object _onUnmatchedItemSelect = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onUnmatchedItemSelect"));
java.lang.Object _onVisibleChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onVisibleChange"));
java.lang.Object _onContentUpdate = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onContentUpdate"));
java.lang.Object _onRender = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onRender"));
java.lang.Object _onWidthChange = GetterUtil.getObject((java.lang.Object)request.getAttribute("alloy:textboxlist:onWidthChange"));

_updateOptions(options, "alwaysShowContainer", _alwaysShowContainer);
_updateOptions(options, "applyLocalFilter", _applyLocalFilter);
_updateOptions(options, "autoHighlight", _autoHighlight);
_updateOptions(options, "boundingBox", _boundingBox);
_updateOptions(options, "button", _button);
_updateOptions(options, "contentBox", _contentBox);
_updateOptions(options, "cssClass", _cssClass);
_updateOptions(options, "dataSource", _dataSource);
_updateOptions(options, "dataSourceType", _dataSourceType);
_updateOptions(options, "delimChar", _delimChar);
_updateOptions(options, "destroyed", _destroyed);
_updateOptions(options, "disabled", _disabled);
_updateOptions(options, "focused", _focused);
_updateOptions(options, "forceSelection", _forceSelection);
_updateOptions(options, "height", _height);
_updateOptions(options, "hideClass", _hideClass);
_updateOptions(options, "textboxlistId", _textboxlistId);
_updateOptions(options, "initialized", _initialized);
_updateOptions(options, "input", _input);
_updateOptions(options, "matchKey", _matchKey);
_updateOptions(options, "maxResultsDisplayed", _maxResultsDisplayed);
_updateOptions(options, "minQueryLength", _minQueryLength);
_updateOptions(options, "queryDelay", _queryDelay);
_updateOptions(options, "queryInterval", _queryInterval);
_updateOptions(options, "queryMatchCase", _queryMatchCase);
_updateOptions(options, "queryMatchContains", _queryMatchContains);
_updateOptions(options, "queryQuestionMark", _queryQuestionMark);
_updateOptions(options, "render", _render);
_updateOptions(options, "rendered", _rendered);
_updateOptions(options, "schema", _schema);
_updateOptions(options, "schemaType", _schemaType);
_updateOptions(options, "srcNode", _srcNode);
_updateOptions(options, "strings", _strings);
_updateOptions(options, "suppressInputUpdate", _suppressInputUpdate);
_updateOptions(options, "tabIndex", _tabIndex);
_updateOptions(options, "typeAhead", _typeAhead);
_updateOptions(options, "typeAheadDelay", _typeAheadDelay);
_updateOptions(options, "uniqueName", _uniqueName);
_updateOptions(options, "visible", _visible);
_updateOptions(options, "width", _width);
_updateOptions(options, "afterAlwaysShowContainerChange", _afterAlwaysShowContainerChange);
_updateOptions(options, "afterApplyLocalFilterChange", _afterApplyLocalFilterChange);
_updateOptions(options, "afterAutoHighlightChange", _afterAutoHighlightChange);
_updateOptions(options, "afterBoundingBoxChange", _afterBoundingBoxChange);
_updateOptions(options, "afterButtonChange", _afterButtonChange);
_updateOptions(options, "afterContainerCollapse", _afterContainerCollapse);
_updateOptions(options, "afterContainerExpand", _afterContainerExpand);
_updateOptions(options, "afterContainerPopulate", _afterContainerPopulate);
_updateOptions(options, "afterContentBoxChange", _afterContentBoxChange);
_updateOptions(options, "afterCssClassChange", _afterCssClassChange);
_updateOptions(options, "afterDataError", _afterDataError);
_updateOptions(options, "afterDataRequest", _afterDataRequest);
_updateOptions(options, "afterDataReturn", _afterDataReturn);
_updateOptions(options, "afterDataSourceChange", _afterDataSourceChange);
_updateOptions(options, "afterDataSourceTypeChange", _afterDataSourceTypeChange);
_updateOptions(options, "afterDelimCharChange", _afterDelimCharChange);
_updateOptions(options, "afterDestroy", _afterDestroy);
_updateOptions(options, "afterDestroyedChange", _afterDestroyedChange);
_updateOptions(options, "afterDisabledChange", _afterDisabledChange);
_updateOptions(options, "afterFocusedChange", _afterFocusedChange);
_updateOptions(options, "afterForceSelectionChange", _afterForceSelectionChange);
_updateOptions(options, "afterHeightChange", _afterHeightChange);
_updateOptions(options, "afterHideClassChange", _afterHideClassChange);
_updateOptions(options, "afterIdChange", _afterIdChange);
_updateOptions(options, "afterInit", _afterInit);
_updateOptions(options, "afterInitializedChange", _afterInitializedChange);
_updateOptions(options, "afterInputChange", _afterInputChange);
_updateOptions(options, "afterItemArrowFrom", _afterItemArrowFrom);
_updateOptions(options, "afterItemArrowTo", _afterItemArrowTo);
_updateOptions(options, "afterItemMouseOut", _afterItemMouseOut);
_updateOptions(options, "afterItemMouseOver", _afterItemMouseOver);
_updateOptions(options, "afterItemSelect", _afterItemSelect);
_updateOptions(options, "afterMatchKeyChange", _afterMatchKeyChange);
_updateOptions(options, "afterMaxResultsDisplayedChange", _afterMaxResultsDisplayedChange);
_updateOptions(options, "afterMinQueryLengthChange", _afterMinQueryLengthChange);
_updateOptions(options, "afterQueryDelayChange", _afterQueryDelayChange);
_updateOptions(options, "afterQueryIntervalChange", _afterQueryIntervalChange);
_updateOptions(options, "afterQueryMatchCaseChange", _afterQueryMatchCaseChange);
_updateOptions(options, "afterQueryMatchContainsChange", _afterQueryMatchContainsChange);
_updateOptions(options, "afterQueryQuestionMarkChange", _afterQueryQuestionMarkChange);
_updateOptions(options, "afterRenderChange", _afterRenderChange);
_updateOptions(options, "afterRenderedChange", _afterRenderedChange);
_updateOptions(options, "afterSchemaChange", _afterSchemaChange);
_updateOptions(options, "afterSchemaTypeChange", _afterSchemaTypeChange);
_updateOptions(options, "afterSelectionEnforce", _afterSelectionEnforce);
_updateOptions(options, "afterSrcNodeChange", _afterSrcNodeChange);
_updateOptions(options, "afterStringsChange", _afterStringsChange);
_updateOptions(options, "afterSuppressInputUpdateChange", _afterSuppressInputUpdateChange);
_updateOptions(options, "afterTabIndexChange", _afterTabIndexChange);
_updateOptions(options, "afterTextboxBlur", _afterTextboxBlur);
_updateOptions(options, "afterTextboxChange", _afterTextboxChange);
_updateOptions(options, "afterTextboxFocus", _afterTextboxFocus);
_updateOptions(options, "afterTextboxKey", _afterTextboxKey);
_updateOptions(options, "afterTypeAhead", _afterTypeAhead);
_updateOptions(options, "afterTypeAheadChange", _afterTypeAheadChange);
_updateOptions(options, "afterTypeAheadDelayChange", _afterTypeAheadDelayChange);
_updateOptions(options, "afterUniqueNameChange", _afterUniqueNameChange);
_updateOptions(options, "afterUnmatchedItemSelect", _afterUnmatchedItemSelect);
_updateOptions(options, "afterVisibleChange", _afterVisibleChange);
_updateOptions(options, "afterContentUpdate", _afterContentUpdate);
_updateOptions(options, "afterRender", _afterRender);
_updateOptions(options, "afterWidthChange", _afterWidthChange);
_updateOptions(options, "onAlwaysShowContainerChange", _onAlwaysShowContainerChange);
_updateOptions(options, "onApplyLocalFilterChange", _onApplyLocalFilterChange);
_updateOptions(options, "onAutoHighlightChange", _onAutoHighlightChange);
_updateOptions(options, "onBoundingBoxChange", _onBoundingBoxChange);
_updateOptions(options, "onButtonChange", _onButtonChange);
_updateOptions(options, "onContainerCollapse", _onContainerCollapse);
_updateOptions(options, "onContainerExpand", _onContainerExpand);
_updateOptions(options, "onContainerPopulate", _onContainerPopulate);
_updateOptions(options, "onContentBoxChange", _onContentBoxChange);
_updateOptions(options, "onCssClassChange", _onCssClassChange);
_updateOptions(options, "onDataError", _onDataError);
_updateOptions(options, "onDataRequest", _onDataRequest);
_updateOptions(options, "onDataReturn", _onDataReturn);
_updateOptions(options, "onDataSourceChange", _onDataSourceChange);
_updateOptions(options, "onDataSourceTypeChange", _onDataSourceTypeChange);
_updateOptions(options, "onDelimCharChange", _onDelimCharChange);
_updateOptions(options, "onDestroy", _onDestroy);
_updateOptions(options, "onDestroyedChange", _onDestroyedChange);
_updateOptions(options, "onDisabledChange", _onDisabledChange);
_updateOptions(options, "onFocusedChange", _onFocusedChange);
_updateOptions(options, "onForceSelectionChange", _onForceSelectionChange);
_updateOptions(options, "onHeightChange", _onHeightChange);
_updateOptions(options, "onHideClassChange", _onHideClassChange);
_updateOptions(options, "onIdChange", _onIdChange);
_updateOptions(options, "onInit", _onInit);
_updateOptions(options, "onInitializedChange", _onInitializedChange);
_updateOptions(options, "onInputChange", _onInputChange);
_updateOptions(options, "onItemArrowFrom", _onItemArrowFrom);
_updateOptions(options, "onItemArrowTo", _onItemArrowTo);
_updateOptions(options, "onItemMouseOut", _onItemMouseOut);
_updateOptions(options, "onItemMouseOver", _onItemMouseOver);
_updateOptions(options, "onItemSelect", _onItemSelect);
_updateOptions(options, "onMatchKeyChange", _onMatchKeyChange);
_updateOptions(options, "onMaxResultsDisplayedChange", _onMaxResultsDisplayedChange);
_updateOptions(options, "onMinQueryLengthChange", _onMinQueryLengthChange);
_updateOptions(options, "onQueryDelayChange", _onQueryDelayChange);
_updateOptions(options, "onQueryIntervalChange", _onQueryIntervalChange);
_updateOptions(options, "onQueryMatchCaseChange", _onQueryMatchCaseChange);
_updateOptions(options, "onQueryMatchContainsChange", _onQueryMatchContainsChange);
_updateOptions(options, "onQueryQuestionMarkChange", _onQueryQuestionMarkChange);
_updateOptions(options, "onRenderChange", _onRenderChange);
_updateOptions(options, "onRenderedChange", _onRenderedChange);
_updateOptions(options, "onSchemaChange", _onSchemaChange);
_updateOptions(options, "onSchemaTypeChange", _onSchemaTypeChange);
_updateOptions(options, "onSelectionEnforce", _onSelectionEnforce);
_updateOptions(options, "onSrcNodeChange", _onSrcNodeChange);
_updateOptions(options, "onStringsChange", _onStringsChange);
_updateOptions(options, "onSuppressInputUpdateChange", _onSuppressInputUpdateChange);
_updateOptions(options, "onTabIndexChange", _onTabIndexChange);
_updateOptions(options, "onTextboxBlur", _onTextboxBlur);
_updateOptions(options, "onTextboxChange", _onTextboxChange);
_updateOptions(options, "onTextboxFocus", _onTextboxFocus);
_updateOptions(options, "onTextboxKey", _onTextboxKey);
_updateOptions(options, "onTypeAhead", _onTypeAhead);
_updateOptions(options, "onTypeAheadChange", _onTypeAheadChange);
_updateOptions(options, "onTypeAheadDelayChange", _onTypeAheadDelayChange);
_updateOptions(options, "onUniqueNameChange", _onUniqueNameChange);
_updateOptions(options, "onUnmatchedItemSelect", _onUnmatchedItemSelect);
_updateOptions(options, "onVisibleChange", _onVisibleChange);
_updateOptions(options, "onContentUpdate", _onContentUpdate);
_updateOptions(options, "onRender", _onRender);
_updateOptions(options, "onWidthChange", _onWidthChange);
%>

<%@ include file="init-ext.jsp" %>